### PR TITLE
Possibility to hide Add in window after action

### PR DESCRIPTION
**Pull request by csbubbles**

### CODE REVIEW

**Comment by csbubbles** [comment]
@FastNinja I've moved the PR from Bitbucket to GitHub. So you could approve it and merge if needed. It would be nice if you integrated that CI you are using with the code reviews, so it wouldn't let merge if the build for the PR fails.

@pstraszak We've moved from Bitbucket to GitHub, I sent you a request to add you to "collaborators" here if you are okay with it.

\+ @gusarov 
\+ @greinerk

**Comment by FastNinja** [comment]
@csbubbles  oh Thanks a lot you copied it across!

**Comment by FastNinja** [comment]
Awesome job. I have integrated CI !

**Comment by csbubbles** [comment]
@FastNinja You'd rather remove your commit with modified `Connect.cs`, and merge the pull request. As your fix is not related to this review. And then create another PR with the fix. Otherwise, you kind of mix things up and create sort of a mess.

Update: Sorry, it looks like the PR can't get through without that change as that file's encoding was changed in it somehow.

**Comment by csbubbles** [comment]
@FastNinja Okay, fixed. Please proceed with the merge if the change looks okay.

**Comment by FastNinja** [comment]
@csbubbles  let me check if that works as intended. I will take MSI from appveryer then install it and verify the functionality...

**Pull request merged**
